name: Building

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env: 
      DOCKER_USER: pioltini
      DOCKER_PASSWORD: dckr_pat_Qhdha354sYakg1ymoiqix0ejXRg
      REPOSITORY: study-api
      
    steps:
    - uses: actions/checkout@v3
    - name: docker login

      run: |
        docker login -u pioltini -p dckr_pat_Qhdha354sYakg1ymoiqix0ejXRg
    - name: build image
      run: docker build -t pioltini/study-api .
    - name: push to registry
      run: docker push pioltini/sutdy-api